# SPDX-FileCopyrightText: TNG Technology Consulting GmbH
#
# SPDX-License-Identifier: Apache-2.0
name: "Testcases for tools-python"

on:
  workflow_dispatch:

jobs:
  run-testcases:
    name: "Run Testcases"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      # user tool specific section starts here

      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel setuptools_scm build
          python -m build -nwx .
          python -m pip install --upgrade ./dist/*.whl
        shell: bash
      - name: Run python scripts that use tools-python to create input file
        id: generate-input
        run: |
          python spdx-tools-python-solver/testcase1.py -t generationMinimal.xml
          python spdx-tools-python-solver/testcase2.py -t generationBaselineSbom.xml
          python spdx-tools-python-solver/testcase3.py -t generationDocument.xml
          python spdx-tools-python-solver/testcase4.py -t generationFile.xml
          python spdx-tools-python-solver/testcase5.py -t generationPackage.xml
          python spdx-tools-python-solver/testcase6.py -t generationSnippet.xml
          python spdx-tools-python-solver/testcase8.py -t generationLicense.xml

      # user tool specific section ends here

      - name: Download testbed fat jar
        id: download-testbed-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci-cd-testbed.yaml
          branch: master
          name: testbed-artifact

      - name: Run test case
        # provide the -t flag with the name of the test case that the input file (-f) attempts to solve
        # look up the README for a list of possible test case names
        run: |
          java -jar testbed-*-all.jar -t generationMinimalTest -f generationMinimal.xml
          java -jar testbed-*-all.jar -t generationBaselineSbomTest -f generationBaselineSbom.xml
          java -jar testbed-*-all.jar -t generationDocumentTest -f generationDocument.xml
          java -jar testbed-*-all.jar -t generationFileTest -f generationFile.xml
          java -jar testbed-*-all.jar -t generationPackageTest -f generationPackage.xml
          java -jar testbed-*-all.jar -t generationSnippetTest -f generationSnippet.xml
          java -jar testbed-*-all.jar -t generationLicenseTest -f generationLicense.xml
